package com.rafaellor.forumhub.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.rafaellor.forumhub.dto.TopicCreateDto;
import com.rafaellor.forumhub.dto.TopicResponseDto;
import com.rafaellor.forumhub.model.Topic;
import com.rafaellor.forumhub.model.User; // Added import for User
import com.rafaellor.forumhub.repository.TopicRepository;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser; // Added for simulating authenticated user
import org.springframework.test.web.servlet.MockMvc;

import java.time.LocalDateTime;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(TopicController.class)
class TopicControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    private TopicRepository topicRepository;

    public TopicControllerTest(TopicRepository topicRepository) {
        this.topicRepository = topicRepository;
    }

    @Configuration
    static class TestConfig {
        @Bean
        public TopicRepository topicRepository() {
            return mock(TopicRepository.class);
        }
    }

    @Test
    @DisplayName("Should return 201 Created when creating a valid topic with authenticated user")
    @WithMockUser(username = "testuser", roles = "USER") // Simulate an authenticated user
    void createTopicScenario1() throws Exception {
        TopicCreateDto createDto = new TopicCreateDto();
        createDto.setTitle("New Test Title");
        createDto.setMessage("New Test Message for controller");
        // Removed: createDto.setAuthor("Controller Author"); // Author is now from authenticated user
        createDto.setCourse("Controller Course");

        // Prepare a mock User for the authenticated principal with correct constructor
        User mockUser = new User(1L, "testuser", "hashedpassword"); // Corrected User constructor

        // Mock the behavior of topicRepository.save
        // The Topic constructor now expects a User object
        Topic savedTopic = new Topic(createDto.getTitle(), createDto.getMessage(), mockUser, createDto.getCourse());
        // Set ID and creation date manually for the mock savedTopic, as they would be generated by DB
        savedTopic.setId(1L);
        savedTopic.setCreationDate(LocalDateTime.now());
        savedTopic.setStatus(true);


        when(topicRepository.existsByTitle(anyString())).thenReturn(false);
        when(topicRepository.existsByMessage(anyString())).thenReturn(false);
        when(topicRepository.save(any(Topic.class))).thenReturn(savedTopic);

        mockMvc.perform(post("/topics")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(createDto)))
                .andExpect(status().isCreated())
                .andExpect(jsonPath("$.id").value(savedTopic.getId()))
                .andExpect(jsonPath("$.title").value(createDto.getTitle()))
                .andExpect(jsonPath("$.authorUsername").value(mockUser.getUsername())); // Changed to authorUsername

        verify(topicRepository, times(1)).save(any(Topic.class));
    }

    @Test
    @DisplayName("Should return 400 Bad Request when creating a topic with duplicate title")
    @WithMockUser(username = "testuser", roles = "USER")
    void createTopicScenario2() throws Exception {
        TopicCreateDto createDto = new TopicCreateDto();
        createDto.setTitle("Existing Title");
        createDto.setMessage("Unique Message");
        createDto.setCourse("Course");

        when(topicRepository.existsByTitle(anyString())).thenReturn(true);

        mockMvc.perform(post("/topics")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(createDto)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.title").value("Title already exists"));
    }

    @Test
    @DisplayName("Should return 400 Bad Request when creating a topic with duplicate message")
    @WithMockUser(username = "testuser", roles = "USER")
    void createTopicScenario3() throws Exception {
        TopicCreateDto createDto = new TopicCreateDto();
        createDto.setTitle("Unique Title");
        createDto.setMessage("Existing Message");
        createDto.setCourse("Course");

        when(topicRepository.existsByTitle(anyString())).thenReturn(false);
        when(topicRepository.existsByMessage(anyString())).thenReturn(true);

        mockMvc.perform(post("/topics")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(createDto)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message").value("Message already exists"));
    }

    @Test
    @DisplayName("Should return 400 Bad Request when creating an invalid topic (e.g., blank title)")
    @WithMockUser(username = "testuser", roles = "USER")
    void createTopicScenario4() throws Exception {
        TopicCreateDto createDto = new TopicCreateDto();
        createDto.setTitle(""); // Invalid
        createDto.setMessage("Valid Message");
        createDto.setCourse("Course");

        mockMvc.perform(post("/topics")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(createDto)))
                .andExpect(status().isBadRequest());
    }

    @Test
    @DisplayName("Should return 200 OK and a list of topics when calling getAllTopics")
    @WithMockUser(username = "testuser", roles = "USER") // Authentication not strictly needed for GET, but good practice
    void getAllTopicsScenario() throws Exception {
        User mockAuthor1 = new User(10L, "author1", "pass"); // Corrected User constructor
        User mockAuthor2 = new User(11L, "author2", "pass"); // Corrected User constructor

        Topic topic1 = new Topic(1L, "Title 1", "Message 1", LocalDateTime.now(), true, mockAuthor1, "Course 1");
        Topic topic2 = new Topic(2L, "Title 2", "Message 2", LocalDateTime.now(), false, mockAuthor2, "Course 2");
        List<Topic> topics = List.of(topic1, topic2);

        when(topicRepository.findAll()).thenReturn(topics);

        mockMvc.perform(get("/topics"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$[0].title").value("Title 1"))
                .andExpect(jsonPath("$[0].authorUsername").value("author1")) // Changed to authorUsername
                .andExpect(jsonPath("$[1].authorUsername").value("author2")); // Changed to authorUsername

        verify(topicRepository, times(1)).findAll();
    }

    @Test
    @DisplayName("Should return 200 OK and the topic when calling getTopicById with existing ID")
    @WithMockUser(username = "testuser", roles = "USER")
    void getTopicByIdScenario1() throws Exception {
        Long topicId = 1L;
        User mockAuthor = new User(10L, "singleuser", "pass"); // Corrected User constructor
        Topic topic = new Topic(topicId, "Single Topic", "Details", LocalDateTime.now(), true, mockAuthor, "Dev");

        when(topicRepository.findById(topicId)).thenReturn(Optional.of(topic));

        mockMvc.perform(get("/topics/{id}", topicId))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.id").value(topicId))
                .andExpect(jsonPath("$.title").value("Single Topic"))
                .andExpect(jsonPath("$.authorUsername").value("singleuser")); // Changed to authorUsername

        verify(topicRepository, times(1)).findById(topicId);
    }

    @Test
    @DisplayName("Should return 404 Not Found when calling getTopicById with non-existing ID")
    @WithMockUser(username = "testuser", roles = "USER")
    void getTopicByIdScenario2() throws Exception {
        Long topicId = 99L;
        when(topicRepository.findById(topicId)).thenReturn(Optional.empty());

        mockMvc.perform(get("/topics/{id}", topicId))
                .andExpect(status().isNotFound());

        verify(topicRepository, times(1)).findById(topicId);
    }

    @Test
    @DisplayName("Should return 200 OK when updating an existing topic")
    @WithMockUser(username = "testuser", roles = "USER")
    void updateTopicScenario1() throws Exception {
        Long topicId = 1L;
        User mockAuthor = new User(10L, "originalauthor", "pass"); // Corrected User constructor
        Topic existingTopic = new Topic(topicId, "Original Title", "Original Message", LocalDateTime.now(), true, mockAuthor, "Course");
        TopicCreateDto updateDto = new TopicCreateDto();
        updateDto.setTitle("Updated Title");
        updateDto.setMessage("Updated Message");
        // No setAuthor for updateDto
        updateDto.setCourse("Course"); // Keep course as original or set to a new value for update

        when(topicRepository.findById(topicId)).thenReturn(Optional.of(existingTopic));
        when(topicRepository.existsByTitle(anyString())).thenReturn(false);
        when(topicRepository.existsByMessage(anyString())).thenReturn(false);

        mockMvc.perform(put("/topics/{id}", topicId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(updateDto)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.title").value("Updated Title"))
                .andExpect(jsonPath("$.message").value("Updated Message"))
                .andExpect(jsonPath("$.course").value(updateDto.getCourse())) // Use updated course for assertion
                .andExpect(jsonPath("$.authorUsername").value("originalauthor")); // Still original author's username

        verify(topicRepository, times(1)).findById(topicId);
    }

    @Test
    @DisplayName("Should return 404 Not Found when updating a non-existing topic")
    @WithMockUser(username = "testuser", roles = "USER")
    void updateTopicScenario2() throws Exception {
        Long topicId = 99L;
        TopicCreateDto updateDto = new TopicCreateDto();
        updateDto.setTitle("New Title");
        updateDto.setMessage("New Message");
        updateDto.setCourse("Course");

        when(topicRepository.findById(topicId)).thenReturn(Optional.empty());

        mockMvc.perform(put("/topics/{id}", topicId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(updateDto)))
                .andExpect(status().isNotFound());

        verify(topicRepository, times(1)).findById(topicId);
    }

    @Test
    @DisplayName("Should return 400 Bad Request when updating topic with duplicate title")
    @WithMockUser(username = "testuser", roles = "USER")
    void updateTopicScenario3() throws Exception {
        Long topicId = 1L;
        User mockAuthor = new User(10L, "originalauthor", "pass"); // Corrected User constructor
        Topic existingTopic = new Topic(topicId, "Original Title", "Original Message", LocalDateTime.now(), true, mockAuthor, "Course");
        TopicCreateDto updateDto = new TopicCreateDto();
        updateDto.setTitle("Another Existing Title");
        updateDto.setMessage("Original Message");
        updateDto.setCourse("Course");

        when(topicRepository.findById(topicId)).thenReturn(Optional.of(existingTopic));
        when(topicRepository.existsByTitle(updateDto.getTitle())).thenReturn(true);

        mockMvc.perform(put("/topics/{id}", topicId)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(updateDto)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.title").value("Title already exists"));
    }

    @Test
    @DisplayName("Should return 204 No Content when deleting an existing topic")
    @WithMockUser(username = "testuser", roles = "USER")
    void deleteTopicScenario1() throws Exception {
        Long topicId = 1L;
        when(topicRepository.existsById(topicId)).thenReturn(true);
        doNothing().when(topicRepository).deleteById(topicId);

        mockMvc.perform(delete("/topics/{id}", topicId))
                .andExpect(status().isNoContent());

        verify(topicRepository, times(1)).existsById(topicId);
        verify(topicRepository, never()).deleteById(anyLong());
    }

    @Test
    @DisplayName("Should return 404 Not Found when deleting a non-existing topic")
    @WithMockUser(username = "testuser", roles = "USER")
    void deleteTopicScenario2() throws Exception {
        Long topicId = 99L;
        when(topicRepository.existsById(topicId)).thenReturn(false);

        mockMvc.perform(delete("/topics/{id}", topicId))
                .andExpect(status().isNotFound());

        verify(topicRepository, times(1)).existsById(topicId);
        verify(topicRepository, never()).deleteById(anyLong());
    }
}
